Repository wecode-bootcamp-korea/AGEOSTE-frontend, pull requests merged in 2021-01, with the labels that each got.

#4 [16기 유재현] AGEOSTE-frontend Add:"Navbar Components"
  public/images/kakao.png
  public/images/logo.png
  src/Components/Navbar/Components/NavbarMenu.js
  src/Components/Navbar/Components/NavbarUser.js
  src/Components/Navbar/Navbar.js
  src/Components/Navbar/Navbar.scss
  src/Pages/Main/Main.js
  src/Styles/common.scss
  src/Styles/reset.scss
  src/index.js
Labels: Status: 리뷰 진행중, Status: 추가 기능 구현중

#3 [16기 김승환] AGEOSTE-frontend Modify: 수정 요청 사항 반영, 컴포넌트 이름 수정 Add: category title 레이아웃 추가
  package-lock.json
  package.json
  src/Pages/Product/Product.js
  src/Pages/ProductList/Components/Product.js
  src/Pages/ProductList/ProductList.js
  src/Pages/ProductList/ProductList.scss
  src/Pages/ProductList/data.js
  src/Routes.js
  src/index.js
Labels: Status: 리뷰 요청

#5 [16기 유재현] AGEOSTE-frontend Footer Modify:리뷰반영 및 폴더구조 변경 완료
  src/Components/Footer/Components/FooterMemberShip/FooterMemberShip.js
  src/Components/Footer/Components/FooterMemberShip/FooterMemberShip.scss
  src/Components/Footer/Components/FooterSubMenu/FooterList.js
  src/Components/Footer/Components/FooterSubMenu/FooterSubMenu.js
  src/Components/Footer/Components/FooterSubMenu/FooterSubMenu.scss
  src/Components/Footer/Components/FooterTopMenu/FooterTopMenu.js
  src/Components/Footer/Components/FooterTopMenu/FooterTopMenu.scss
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
  src/Components/Footer/data/FooterDatas.js
  src/Pages/Main/Main.js
  src/Styles/common.scss
Labels: Status: 리뷰 요청

#1 [16기 박영호] AGEOSTE-frontend Modify: 로그인페이지 conflict 오류 수정 및 기능 구현
  package-lock.json
  package.json
  public/images/Ageoste.png
  public/images/Membership.png
  public/index.html
  src/Pages/Login/Data/config.js
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/ProductList/ProductList.scss
  src/Styles/common.scss
  src/index.js
Labels: Status: 수정 요청, Status: 컨플릭트 해결 요청

#7 [16기 박영호] AGEOSTE-frontend Modify: 회원가입 기능 구현 및 체크박스 로직 일부 수정, 컨플릭트 오류수정
  src/Pages/Signup/Data/Config.js
  src/Pages/Signup/Signup.js
  src/Pages/Signup/Signup.scss
  src/Routes.js
  src/index.js
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중, Status: 컨플릭트 해결 요청

#6 [16기 박영호] AGEOSTE-frontend Modify: "마이 페이지 이메일 인증구현"
  public/data/UserData.json
  public/data/account.json
  public/data/data.json
  public/images/Gold.png
  public/images/Silver.png
  public/images/Vip.png
  public/images/logo.png
  src/Pages/Login/Data/config.js
  src/Pages/Myprofile/Data/config.js
  src/Pages/Myprofile/Myprofile.js
  src/Pages/Myprofile/Myprofile.scss
  src/Pages/Signup/Data/Config.js
  src/Pages/Signup/Signup.js
  src/Routes.js
  src/index.js
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중, Status: 컨플릭트 해결 요청

#10 [16기 유재현] AGEOSTE-frontend Main 페이지 컨플릭트 해결완료
  package-lock.json
  package.json
  public/data/data.json
  public/images/mainSecondBg.webp
  public/images/mainTopBg.webp
  src/Components/CollectionSlider/CollectionSlider.js
  src/Components/CollectionSlider/CollectionSlider.scss
  src/Components/Navbar/Navbar.js
  src/Components/Navbar/Navbar.scss
  src/Components/ProductList/ProductList.js
  src/Components/ProductList/ProductList.scss
  src/Components/ProductListSlider/ProductListSlider.js
  src/Components/ProductListSlider/ProductListSlider.scss
  src/Components/WearCollection/WearCollection.js
  src/Components/WearCollection/WearCollection.scss
  src/Pages/Main/Components/MainPromotions/MainPromotions.js
  src/Pages/Main/Components/MainPromotions/MainPromotions.scss
  src/Pages/Main/Components/MainSalesList/MainSalesList.js
  src/Pages/Main/Components/MainSalesList/MainSalesList.scss
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/Pages/Main/data/MainData.js
  src/Pages/Product/Product.js
  src/Pages/ProductDetail/ProductDetail.js
  src/Routes.js
  src/Styles/common.scss
  src/config/Server.js
Labels: Status: 리뷰 요청

#11 [16기 유재현] AGEOSTE-frontend 상세페이지 작업 완료 기능 구현 완료
  package.json
  src/Components/Footer/Components/FooterMemberShip/FooterMemberShip.js
  src/Pages/Main/Main.js
  src/Pages/ProductDetail/DetailImgSession/DetailImgSession.js
  src/Pages/ProductDetail/DetailImgSession/DetailImgSession.scss
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/ProductDetail/ProductDetail.scss
  src/Pages/ProductDetail/ProductDetailCart/ProductDetailCart.js
  src/Pages/ProductDetail/ProductDetailCart/ProductDetailCart.scss
  src/Pages/ProductDetail/ProductPriceAndRating/ProductPriceAndRating.js
  src/Pages/ProductDetail/ProductPriceAndRating/ProductPriceAndRating.scss
  src/Pages/ProductDetail/ProductSize/ProductSize.js
  src/Pages/ProductDetail/ProductSize/ProductSize.scss
  src/Routes.js
Labels: Status: 리뷰 요청

#8 [16기 유재현] AGEOSTE-frontend Modify: Navbar 컨플릭트 해결 완료
  src/Components/Navbar/Components/NavbarMenu.js
  src/Components/Navbar/Components/NavbarMenu/NavbarMenu.js
  src/Components/Navbar/Components/NavbarMenu/NavbarMenu.scss
  src/Components/Navbar/Components/NavbarMenu/NavbarSubList.js
  src/Components/Navbar/Components/NavbarMenu/NavbarSubMenu.js
  src/Components/Navbar/Components/NavbarUser/NavbarUser.js
  src/Components/Navbar/Components/NavbarUser/NavbarUser.scss
  src/Components/Navbar/Navbar.js
  src/Components/Navbar/Navbar.scss
  src/Components/Navbar/data/NavbarData.js
  src/Routes.js
Labels: Status: 리뷰 요청
